<template>
    <div class="terms">
        <section class="jumbotron terms__header bg-gradient-primary">
            <div class="container text-center">
                <h1 class="header text-white">Terms and Condition</h1>
                <p class="lead">This is to keep our customers informed and abreast of happenings in the crypto world.</p>
            </div>
        </section>

        <section class="slice terms__content">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <p>Thank you for accessing stebabxchange.com website operated by Stebab Xchange. We respect your data aand privacy and want to protect your personal information. To learn more, please read this Privacy Policy.</p>
                        <p>Data protection is a matter of trust and your privacy is important to us. We shall therefore only use your name and other information which relates to you in the manner set out in this Privacy Policy. We will only collect information where it is necessary for us to do so and we will only collect information if it is relevant to our dealings with you.</p>
                        <p>We will only keep your information for as long as we are either required to by law or as is relevant for the purposes for which it was collected. You can visit the Site and browse without having to provide personal details. During your visit to the Site you remain anonymous and at no time can we identify you unless you have an account on the Site and log on with your user name and password.</p>
                        <p>This document is an electronic record in terms of the National Information Technology Development Agency Act, 2014 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the National Information Technology Development Agency Act, 2014. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                        <p>Welcome to the stebabxchange.com website (the "Site"). These terms &amp; conditions ("Terms and Conditions") apply to the Site, and all of its divisions, subsidiaries, and affiliate operated Internet sites which reference these Terms and Conditions. This website is owned and operated by Stebab Xchange. For the purposes of this website, "seller", "buyer", "we", "us" and "our" all refer stebabxchange.com</p>
                        <p class="font-weight-bold">YOU ACCEPT THESE TERMS OF USE BY ACCESSING OR OTHERWISE BROWSING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS IN THIS AGREEMENT, SO PLEASE READ THIS AGREEMENT CAREFULLY BEFORE PROCEEDING</p>
                    

                        <h3>Cookies</h3>
                        <p>The acceptance of cookies is not a requirement for visiting the Site. However, we would like to point out that the use of the 'basket' functionality on the Site and ordering is only possible with the activation of cookies. Cookies are tiny text files which identify your computer to our server as a unique user when you visit certain pages on the Site and they are stored by your Internet browser on your computer's hard drive. Cookies can be used to recognize your Internet Protocol address, saving you time while you are on, or want to enter, the Site. We only use cookies for your convenience in using the Site (for example to remember who you are when you want to amend your shopping cart without having to re-enter your email address) and not for obtaining or using any other information about you (for example targeted advertising). Your browser can be set to not accept cookies, but this would restrict your use of the Site. Please accept our assurance that our use of cookies does not contain any personal or private details and are free from viruses. If you want to find out more information about cookies, go to http://www.allaboutcookies.org or to find out about removing them from your browser, go to http://www.allaboutcookies.org/manage-cookies/index.html. </p>
                        

                        <h3>Security</h3>
                        <p>We have in place appropriate technical and security measures to prevent unauthorized or unlawful access to or accidental loss of or destruction or damage to your information. When we collect data through the Site, we collect your personal details on a secure server. We use firewalls on our servers. When we collect payment card details electronically, we use encryption by using Secure Socket Layer (SSL) coding. While we are unable to guarantee 100% security, this makes it hard for a hacker to decrypt your details. You are strongly recommended not to send full credit or debit card details in unencrypted electronic communications with us. We maintain physical, electronic and procedural safeguards in connection with the collection, storage and disclosure of your information. Our security procedures mean that we may occasionally request proof of identity before we disclose personal information to you. You are responsible for protecting against unauthorized access to your password and to your computer.</p>
                    

                        <h3>Indemnity</h3>
                        <p>I hereby fully indemnify StebabXchange, its Directors, agents, privies, assigns, successors,  employees or any other person whomsoever acting under the company's authority or control against any cost, losses, damages, litigation, action, proceeding, expenses (including Attorney's fees),  judicial awards of any kind, or any payments of whatsoever nature made or any cost however incurred, whether directly or indirectly, remotely or otherwise, resulting from any falsehood,  fraud and misrepresentation regards my transactions with the company. 
                        <p>I undertake to be fully responsible for all risks that may arise from the transactions as well or together with all losses which may be suttered by me as a result of any falsehood, fraud and misrepresentation regarding my transaction with the company. </p>
                        <p>This indemnity shall be a continuity obligation in respect of any and all matter connected to or arising from the company processing cryptocurrency transactions.</p>
            
                    </div>
                </div>
            </div>
        </section>

        <cta :message="message" />

    </div>
</template>

<script>
    import CTA from "@/components/features/cta";
    
    export default {
        head(){
            return{

            }
        },

        data(){
            return {
                message: "Ready to start trading with us? We can't wait!"
            }
        },

        components : {
            CTA,
        },

        transitions: 'fade',

    }
</script>

<style lang="scss" scoped>
    .terms {

        &__header{
            padding-top: 12rem;
            color: $white;
        }

        &__content {
            h3 {
                color: $primary;
                margin-top: 3rem;
            }
        }
    }
</style>